# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Vijay Dev'
tagline:          'UI & front-end developer'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://vijaydev.com/
baseurl:          '/'
paginate:         5

categories:       [HTML, CSS, JavaScript, AngularJS, Travel, Personal]

author:
  name:           'Vijay Dev'
  url:            https://twitter.com/vijaydevin

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vijaydevin/vijaydevin.github.io

sass:
  sass_dir: _sass
