# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        '/blog/:year/:title/'
paginate_path:    '/blog/page:num/'

# Setup
title:            'Vijay Dev'
tagline:          'UI & Front-end Developer'
description:      'UI Designer . Front-end Developer . Mobile Ninja'
url:              https://www.vijaydev.com/
baseurl:          'https://www.vijaydev.com/'
paginate:         5
excerpt_separator: "<!-- more -->"

categories:       [HTML, CSS, JavaScript, AngularJS, Travel, Personal]

author:
  name:           'Vijay Dev'
  url:            https://twitter.com/vijaydevin

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/vijaydevin/vijaydevin.github.io

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jemoji
